demo/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'users/enable_otp'
  post 'users/disable_otp'

  devise_for :users

  root to: "home#index", via: [:get, :post]
end

demo/app/models/user.rb
class User < ActiveRecord::Base
  devise :two_factor_authenticatable,
         # Set a unique encryption key for your app.
         # Store your key as an ENV variable and
         # remember to add it to .gitignore
         # if you plan to share your code publicly.
         otp_secret_encryption_key: ENV['ENCRYPTION_KEY']

  devise :registerable, :recoverable, :rememberable,
         :trackable, :validatable
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
  end
end

demo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def disable_otp
    current_user.otp_required_for_login = false
    current_user.save!
    redirect_to home_index_path
  end

  def enable_otp
    current_user.otp_secret = User.generate_otp_secret
    current_user.otp_required_for_login = true
    current_user.save!
    redirect_to home_index_path
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/home_helper.rb
module HomeHelper
end

demo/app/views/home/index.html.erb
<% if !current_user %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Login", new_user_session_path %>
<% end %>

<% if current_user %>
  <% if !current_user.otp_required_for_login %>
    <%= button_to "Enable 2FA", users_enable_otp_path, :method => :post %>
  <% end %>

  <% if current_user.otp_required_for_login %>
    <%= button_to "Disable 2FA", users_disable_otp_path, :method => :post %>
    <%= raw RQRCode::render_qrcode(current_user.otp_provisioning_uri(current_user.email, issuer: "Devise-Two-Factor-Demo"),
                                   :svg,
                                   :level => :l,
                                   :unit => 2) %>
    <br>
  <% end %>
  <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<% end %>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTwoFactorDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_tag :div, flash[:notice] if flash[:notice] %>
<%= content_tag :div, flash[:alert] if flash[:alert] %>

<%= yield %>

</body>
</html>